import { mutation } from "./_generated/server";

export const seedDatabase = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if data already exists
    const existingVehicles = await ctx.db.query("vehicles").take(1);
    if (existingVehicles.length > 0) {
      return "Database already seeded";
    }

    // Sample vehicles data with more variety
    const sampleVehicles = [
      {
        lotNumber: "47832156",
        year: 2020,
        make: "TOYOTA",
        model: "COROLLA",
        bodyStyle: "SEDAN",
        engine: "1.8L 4",
        transmission: "AUTOMATIC",
        fuel: "GASOLINE",
        odometer: 45000,
        primaryDamage: "FRONT END",
        secondaryDamage: "MINOR DENT",
        estimatedRetailValue: 85000,
        currentBid: 25000,
        saleDate: "2024-02-15",
        saleTime: "10:00",
        location: "SÃO PAULO - SP",
        seller: "INSURANCE AUTO AUCTIONS",
        titleType: "CLEAR",
        keys: true,
        images: [],
        status: "upcoming" as const,
        vin: "2T1BURHE5LC123456",
        color: "BRANCO",
        condition: "RUN AND DRIVE",
        grade: "A",
      },
      {
        lotNumber: "47832157",
        year: 2019,
        make: "HONDA",
        model: "CIVIC",
        bodyStyle: "SEDAN",
        engine: "2.0L 4",
        transmission: "CVT",
        fuel: "GASOLINE",
        odometer: 32000,
        primaryDamage: "REAR END",
        estimatedRetailValue: 95000,
        currentBid: 35000,
        saleDate: "2024-02-15",
        saleTime: "10:30",
        location: "RIO DE JANEIRO - RJ",
        seller: "INSURANCE AUTO AUCTIONS",
        titleType: "CLEAR",
        keys: true,
        images: [],
        status: "upcoming" as const,
        vin: "19XFC2F59KE123456",
        color: "PRETO",
        condition: "RUN AND DRIVE",
        grade: "B",
      },
      {
        lotNumber: "47832158",
        year: 2021,
        make: "VOLKSWAGEN",
        model: "JETTA",
        bodyStyle: "SEDAN",
        engine: "1.4L TURBO",
        transmission: "AUTOMATIC",
        fuel: "GASOLINE",
        odometer: 28000,
        primaryDamage: "HAIL",
        estimatedRetailValue: 110000,
        currentBid: 45000,
        saleDate: "2024-02-16",
        saleTime: "09:00",
        location: "BELO HORIZONTE - MG",
        seller: "INSURANCE AUTO AUCTIONS",
        titleType: "CLEAR",
        keys: true,
        images: [],
        status: "live" as const,
        vin: "3VWC57BU8MM123456",
        color: "PRATA",
        condition: "RUN AND DRIVE",
        grade: "A",
      },
      {
        lotNumber: "47832159",
        year: 2018,
        make: "FORD",
        model: "FOCUS",
        bodyStyle: "HATCHBACK",
        engine: "2.0L 4",
        transmission: "AUTOMATIC",
        fuel: "GASOLINE",
        odometer: 65000,
        primaryDamage: "SIDE",
        estimatedRetailValue: 70000,
        currentBid: 22000,
        saleDate: "2024-02-16",
        saleTime: "11:00",
        location: "CURITIBA - PR",
        seller: "INSURANCE AUTO AUCTIONS",
        titleType: "CLEAR",
        keys: false,
        images: [],
        status: "upcoming" as const,
        vin: "1FADP3K28JL123456",
        color: "AZUL",
        condition: "START RUNS DRIVES",
        grade: "C",
      },
      {
        lotNumber: "47832160",
        year: 2022,
        make: "HYUNDAI",
        model: "HB20",
        bodyStyle: "HATCHBACK",
        engine: "1.0L 3",
        transmission: "MANUAL",
        fuel: "FLEX",
        odometer: 15000,
        primaryDamage: "FLOOD",
        estimatedRetailValue: 65000,
        currentBid: 18000,
        saleDate: "2024-02-17",
        saleTime: "14:00",
        location: "SALVADOR - BA",
        seller: "INSURANCE AUTO AUCTIONS",
        titleType: "FLOOD",
        keys: true,
        images: [],
        status: "upcoming" as const,
        vin: "9BWHE21JX24123456",
        color: "VERMELHO",
        condition: "ENGINE START PROGRAM",
        grade: "B",
      },
      {
        lotNumber: "47832161",
        year: 2017,
        make: "CHEVROLET",
        model: "ONIX",
        bodyStyle: "HATCHBACK",
        engine: "1.4L 4",
        transmission: "AUTOMATIC",
        fuel: "FLEX",
        odometer: 78000,
        primaryDamage: "ALL OVER",
        estimatedRetailValue: 55000,
        currentBid: 15000,
        saleDate: "2024-02-17",
        saleTime: "15:30",
        location: "PORTO ALEGRE - RS",
        seller: "INSURANCE AUTO AUCTIONS",
        titleType: "SALVAGE",
        keys: false,
        images: [],
        status: "live" as const,
        vin: "9BGXH48X0HG123456",
        color: "BRANCO",
        condition: "NOT RUN AND DRIVE",
        grade: "D",
      },
      {
        lotNumber: "47832162",
        year: 2023,
        make: "NISSAN",
        model: "KICKS",
        bodyStyle: "SUV",
        engine: "1.6L 4",
        transmission: "CVT",
        fuel: "FLEX",
        odometer: 8000,
        primaryDamage: "FRONT END",
        estimatedRetailValue: 95000,
        currentBid: 42000,
        saleDate: "2024-02-18",
        saleTime: "10:00",
        location: "BRASÍLIA - DF",
        seller: "INSURANCE AUTO AUCTIONS",
        titleType: "CLEAR",
        keys: true,
        images: [],
        status: "upcoming" as const,
        vin: "3N1CN7AP6PL123456",
        color: "CINZA",
        condition: "RUN AND DRIVE",
        grade: "A",
      },
      {
        lotNumber: "47832163",
        year: 2016,
        make: "BMW",
        model: "320I",
        bodyStyle: "SEDAN",
        engine: "2.0L 4 TURBO",
        transmission: "AUTOMATIC",
        fuel: "GASOLINE",
        odometer: 95000,
        primaryDamage: "SIDE",
        secondaryDamage: "REAR END",
        estimatedRetailValue: 120000,
        currentBid: 55000,
        saleDate: "2024-02-18",
        saleTime: "16:00",
        location: "SÃO PAULO - SP",
        seller: "INSURANCE AUTO AUCTIONS",
        titleType: "CLEAR",
        keys: true,
        images: [],
        status: "sold" as const,
        vin: "WBA8E1C59GK123456",
        color: "PRETO",
        condition: "RUN AND DRIVE",
        grade: "B",
      },
    ];

    // Insert vehicles
    for (const vehicle of sampleVehicles) {
      await ctx.db.insert("vehicles", vehicle);
    }

    // Sample auctions with more variety
    const sampleAuctions = [
      {
        name: "Leilão São Paulo - Veículos Premium",
        date: "2024-02-15",
        time: "10:00",
        location: "SÃO PAULO - SP",
        status: "upcoming" as const,
        vehicleCount: 150,
      },
      {
        name: "Leilão Rio de Janeiro - Multimarcas",
        date: "2024-02-16",
        time: "09:00",
        location: "RIO DE JANEIRO - RJ",
        status: "live" as const,
        vehicleCount: 200,
      },
      {
        name: "Leilão Belo Horizonte - Salvage",
        date: "2024-02-17",
        time: "14:00",
        location: "BELO HORIZONTE - MG",
        status: "upcoming" as const,
        vehicleCount: 120,
      },
      {
        name: "Leilão Curitiba - Clean Title",
        date: "2024-02-18",
        time: "11:00",
        location: "CURITIBA - PR",
        status: "upcoming" as const,
        vehicleCount: 80,
      },
      {
        name: "Leilão Salvador - Especial Nordeste",
        date: "2024-02-19",
        time: "15:00",
        location: "SALVADOR - BA",
        status: "upcoming" as const,
        vehicleCount: 95,
      },
    ];

    for (const auction of sampleAuctions) {
      await ctx.db.insert("auctions", auction);
    }

    return "Database seeded successfully with enhanced data";
  },
});
